title: GVSU Game Jam
description: Homepage for providing resources and information regarding the Game Jam event series.
theme: just-the-docs
color_scheme: dark

callouts_opacity: 0.3
callouts:
  important:
    title: Important
    color: red

url: https://gvsu-gamejam.github.io

aux_links:
  Page Repository: https://github.com/GVSU-GameJam/gvsu-gamejam.github.io
  Twitter: https://twitter.com/erik_fredericks
